### ISSUE TITLE
Accepting suggestion part way through keyword doesn't replace rest of keyword

### ISSUE THREAD

**Issue by maxhudson** [dabakovich/react-native-controlled-mentions#31]
`hey @M|ik` 

...accept suggestion with cursor after M 

results in `hey @Mikeik`

**Comment by dabakovich** [comment]
Hi @maxhudson, thanks for your feedback!
Actually, that is expected behavior. The library supports mentions with spaces ("@Max Hudson"), so the most stable flow here is just to replace a string between trigger and cursor position. As result, it should be understandable for the end-user why a mention was added this way and he will take this into account for the future.

**Comment by maxhudson** [comment]
I'm actually a bit unclear why this would be expected still.

Say I type `@M`... then `@Mik`... then I place the cursor back between `@M` and `ik` - I'll get the suggestion for mike, but when I accept it, it only replaces the `M`, not the `ik`, so I end up with `@Mikeik`.

I see why a user might account for this behavior in the future and avoid it, but it's unclear to me how it's a feature.

**Comment by dabakovich** [comment]
I see your point. Maybe it will be more clear in your case to use the `isInsertSpaceAfterMention` property?
So then `@M|ik` will become `@Mike ik`.
Anyway, the main idea is always to replace the value between the trigger (`@`) and the cursor no matter if the cursor at the end of a string or inside.
This behavior is common to a number of messengers (Telegram, Skype).

**Comment by maxhudson** [comment]
You're right - appears to be standard behavior. Probably just impossible to detect reliably/causes other issues
