### ISSUE TITLE
Is there a way to render the view outside of the TextInput? I need to show this in my own view outside the textInput

### ISSUE THREAD

**Issue by shaheer2020** [dabakovich/react-native-controlled-mentions#69]

**Comment by Vahe21** [comment]
use RootSiblingPortal

**Comment by swushi** [comment]
https://github.com/dabakovich/react-native-controlled-mentions/issues/75

**Comment by dabakovich** [comment]
Hi @shaheer2020! Thanks for your feedback.

A new major v3 release is coming, and this issue is one of the main updates.

Now you will be able to use hook for control mention state. The main idea – suggestions rendering now will be fully controlled by user and is extracted from `MentionInput` component.

You can find an example of this here: https://github.com/dabakovich/react-native-controlled-mentions/blob/3.0.0-feat-use-mentions/example/mentions-app.tsx#L90

To install this and play by yourself, please use next commands:
```
yarn add react-native-controlled-mentions@alpha
// or
npm install --save react-native-controlled-mentions@alpha
```
I'll be happy to get some feedback from you before the major update will be released.

**Comment by dabakovich** [comment]
Let's continue the discussion in the duplicating #65.
