### ISSUE TITLE
Is isBottomMentionSuggestionsRender at all there in version 3.0.0-alpha.4 of this library ?

### ISSUE THREAD

**Issue by Sumit2202** [dabakovich/react-native-controlled-mentions#87]

**Comment by dabakovich** [comment]
No, we don't need this property anymore because suggestions render is now completely controlling by user. And you can put suggestions render below the `MentionInput` if you wish. Please, explore this example: https://github.com/dabakovich/react-native-controlled-mentions/blob/3.0/example/mentions-class-component.tsx#L53
